#!/bin/sh
#shellcheck source=.xprofile
. ~/.xprofile

dex -a &
deadd-notification-center &
redshift &
sxhkd &
flameshot &
kdeconnect-indicator &
volumeicon &
xrdb -merge "$XDG_CONFIG_HOME/xrdb/Xresources" && autotheme &
xss-lock killall autotheme && autotheme &
udiskie -t --terminal=ranger &
remaps &
pgrep -fl 'pidswallow -gl' || pidswallow -gl &

ssh-agent "${1:-i3}"
